# <PROJECT_ROOT>/.cargo/config.toml
# 
# reference:
#   https://bevy.org/learn/quick-start/getting-started/setup/#enable-fast-compiles-optional


# cranelift (Nightly Only)
### rustup component add rustc-codegen-cranelift-preview --toolchain nightly
[unstable]
codegen-backend = true

[profile.dev]
codegen-backend = "cranelift"

[profile.dev.package."*"]
codegen-backend = "llvm"


# Generic Sharing (Nightly Only)
[target.x86_64-unknown-linux-gnu]
rustflags = [
    # (Nightly) Make the current crate share its generic instantiations
    "-Zshare-generics=y",
]

[env]
# for running pyo3 in rust
VIRTUAL_ENV = { value = ".venv", relative = true }

